#!/usr/bin/env python3
"""Recommend a practical first Dublin SCATS site for local SUMO work."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rank topology-ready Dublin SCATS sites for local SUMO scenario development."
    )
    parser.add_argument(
        "--traffic-data",
        default="./data/TrafficGeneration/dublin_march_2025/detector_data.csv",
        help="Repo-compatible Dublin traffic profile CSV.",
    )
    parser.add_argument(
        "--site-metadata",
        default="./data/TrafficGeneration/dublin_march_2025/site_metadata.csv",
        help="Dublin metadata CSV generated by preprocess_dublin_scats.py.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=15,
        help="Number of ranked sites to display.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    compat = pd.read_csv(Path(args.traffic_data))
    meta = pd.read_csv(Path(args.site_metadata))

    hourly_columns = [f"h{hour:02d}" for hour in range(24)]
    merged = compat.merge(
        meta[
            [
                "site_id",
                "site_description",
                "region_metadata",
                "lat",
                "long",
                "retained_for_topology",
                "missing_coordinates",
            ]
        ],
        on="site_id",
        how="left",
    )
    merged["daily_total"] = merged[hourly_columns].sum(axis=1)
    merged["peak_hour"] = merged[hourly_columns].max(axis=1)
    merged["offpeak_mean"] = merged[[f"h{hour:02d}" for hour in [0, 1, 2, 3, 4, 22, 23]]].mean(axis=1)
    merged["peak_spread"] = merged["peak_hour"] - merged["offpeak_mean"]

    candidates = merged[
        (merged["retained_for_topology"] == True)
        & (merged["missing_coordinates"] == False)
        & merged["site_description"].notna()
        & (merged["peak_hour"] >= 250)
        & (merged["peak_hour"] <= 700)
    ].copy()

    # Favor sites that are topology-ready, have moderate traffic, and show a clear day/night pattern.
    target_peak = 500.0
    candidates["moderation_score"] = (candidates["peak_hour"] - target_peak).abs()
    ranked = candidates.sort_values(
        ["moderation_score", "peak_spread", "daily_total"],
        ascending=[True, False, False],
    )

    display = ranked[
        [
            "site_id",
            "site_description",
            "region_metadata",
            "lat",
            "long",
            "daily_total",
            "peak_hour",
            "peak_spread",
        ]
    ].head(args.top_n)
    print(display.to_string(index=False))


if __name__ == "__main__":
    main()
