#!/usr/bin/env python3
"""Scaffold a Dublin site folder for SUMO integration."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


README_TEMPLATE = """# Dublin SUMO Scenario for Site {site_id}

This folder scaffolds the SUMO inputs expected by the DesRUTGe traffic pipeline for Dublin SCATS site `{site_id}`.

## Site

- `site_id`: {site_id}
- `description`: {site_description}
- `region`: {region}
- `lat`: {lat}
- `long`: {long}

## Required files

You still need to create or replace the following files with real Dublin SUMO assets:

- `osm.net.xml`
- `miniTAZ.xml`
- `detectors.add.xml`
- `sim.sumocfg`

## Recommended local workflow

1. Download an OpenStreetMap extract that covers the site and nearby approaches.
2. Convert it into a SUMO net with `netconvert`.
3. Open the net in `netedit` and identify the approaches corresponding to this SCATS site.
4. Create `detectors.add.xml` with induction loops on those lanes.
5. Create `miniTAZ.xml` with a single site-centric zone and candidate source/sink edges.
6. Validate the site with:
   - `od2trips -n miniTAZ.xml -d od_file.od -o trips.xml`
   - `duarouter -n osm.net.xml -t trips_via.xml -o routes.rou.xml --additional-files miniTAZ.xml --ignore-errors --no-warnings`
   - `sumo -c sim.sumocfg --no-warnings`

## Notes

- The current repo expects this directory to be named exactly after the site id.
- Once these files are valid, the DesRUTGe SUMO loop can target this site.
"""


SIMCFG_TEMPLATE = """<configuration>
    <input>
        <net-file value="osm.net.xml"/>
        <additional-files value="detectors.add.xml"/>
        <route-files value="routes.rou.xml"/>
    </input>

    <time>
        <begin value="0"/>
    </time>

    <processing>
        <time-to-teleport value="300"/>
    </processing>
</configuration>
"""


TAZ_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <!-- Replace placeholder source/sink edges with real edges from osm.net.xml -->
    <taz id="taz" color="blue">
        <tazSource id="REPLACE_SOURCE_EDGE" weight="1.00"/>
        <tazSink id="REPLACE_SINK_EDGE" weight="1.00"/>
    </taz>
</additional>
"""


DETECTORS_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <!-- Replace placeholder lane/position values with real Dublin site detector placements -->
    <inductionLoop id="site_{site_id}_a" lane="REPLACE_LANE_ID" pos="25.00" period="900.00" file="AM_{site_id}_a.xml"/>
</additional>
"""


OD_TEMPLATE = """$OR;D2
0.00 1.00
1.0
taz taz 100
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a scaffold SUMO folder for one Dublin SCATS site.")
    parser.add_argument("--site-id", required=True, help="Dublin SCATS site id.")
    parser.add_argument(
        "--site-metadata",
        default="./data/TrafficGeneration/dublin_march_2025/site_metadata.csv",
        help="Dublin metadata CSV generated by preprocess_dublin_scats.py.",
    )
    parser.add_argument(
        "--output-root",
        default="./src/machine_learning/training",
        help="Root directory where the site folder should be created.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metadata = pd.read_csv(Path(args.site_metadata), dtype={"site_id": str})
    site_id = str(args.site_id).strip()

    site_rows = metadata[metadata["site_id"].astype(str) == site_id]
    if site_rows.empty:
        raise ValueError(f"Site {site_id} was not found in {args.site_metadata}.")

    site = site_rows.iloc[0]
    site_dir = Path(args.output_root) / site_id
    site_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "README.md": README_TEMPLATE.format(
            site_id=site_id,
            site_description=site.get("site_description", ""),
            region=site.get("region_metadata", ""),
            lat=site.get("lat", ""),
            long=site.get("long", ""),
        ),
        "sim.sumocfg": SIMCFG_TEMPLATE,
        "miniTAZ.xml": TAZ_TEMPLATE,
        "detectors.add.xml": DETECTORS_TEMPLATE.format(site_id=site_id),
        "od_file.od": OD_TEMPLATE,
    }

    for name, contents in files.items():
        path = site_dir / name
        if not path.exists():
            path.write_text(contents, encoding="utf-8")

    print(site_dir)


if __name__ == "__main__":
    main()
